### ISSUE TITLE
testing against 2016.2 with version 1.246+ = OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by yugecin** [JetBrains/intellij-plugin-verifier#48] opened 2020-09-17 15:58 UTC
Hi

We test our plugin against IDE versions 2019.3.3, 2018.1.4, 2020.2, 2017.2, 2016.2, 2019.1.3, 2020.1
Since plugin verifier version 1.246, it always dies with an OOM error once it's checking 2016.2.
It also happens if we only check 2016.2.
If we skip 2016.2, it completes normally.

We reverted to verifier version 1.245, and now it completes successfully again.

Our plugin dependencies are:
```
<depends>com.intellij.modules.lang</depends>
<depends optional="true" config-file="<omitted>">com.intellij.modules.xml</depends>
<depends optional="true" config-file="<omitted>">com.intellij.modules.java</depends>
<depends optional="true" config-file="<omitted>">org.jetbrains.plugins.gradle</depends>
<depends optional="true" config-file="<omitted>">org.intellij.groovy</depends>
<depends optional="true" config-file="<omitted>">JavaScript</depends>
<depends optional="true" config-file="<omitted>">com.jetbrains.php</depends>
<depends optional="true" config-file="<omitted>">Pythonid</depends>
<depends optional="true" config-file="<omitted>">com.intellij.jsp</depends>
<depends optional="true" config-file="<omitted>">org.jetbrains.kotlin</depends>
<depends optional="true" config-file="<omitted>">org.jetbrains.plugins.yaml</depends>
```

output:
```
Scheduled verifications (7):
ourpluginid:4.26.1 against IU-193.6494.35, ourpluginid:4.26.1 against IU-181.5087.20, ourpluginid:4.26.1 against IU-202.6397.94, ourpluginid:4.26.1 against IU-172.3317.76, ourpluginid:4.26.1 against IU-162.1121.32, ourpluginid:4.26.1 against IU-191.7479.19, ourpluginid:4.26.1 against IU-201.6668.121

2020-09-17T14:49:23 [main] INFO  verification - Finished 1 of 7 verifications (in 55.4 s): IU-181.5087.20 against ourpluginid:4.26.1: Compatible. 11 usages of deprecated API. 1 usage of experimental API
2020-09-17T14:49:33 [main] INFO  verification - Finished 2 of 7 verifications (in 65.1 s): IU-191.7479.19 against ourpluginid:4.26.1: Compatible. 27 usages of deprecated API. 1 usage of experimental API
2020-09-17T14:50:05 [main] INFO  verification - Finished 3 of 7 verifications (in 97.5 s): IU-201.6668.121 against ourpluginid:4.26.1: Compatible. 1 usage of scheduled for removal API and 36 usages of deprecated API
2020-09-17T14:50:25 [main] INFO  verification - Finished 4 of 7 verifications (in 115.2 s): IU-193.6494.35 against ourpluginid:4.26.1: Compatible. 1 usage of scheduled for removal API and 29 usages of deprecated API
Exception in thread "main" java.lang.RuntimeException: Worker 'ourpluginid:4.26.1 against IU-162.1121.32' finished with error
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress.waitAllFutures(ConcurrencyUtils.kt:95)
	at com.jetbrains.plugin.structure.base.utils.ExecutorWithProgress.executeTasks(ConcurrencyUtils.kt:61)
	at com.jetbrains.pluginverifier.PluginVerifierRunKt.runSeveralVerifiers(PluginVerifierRun.kt:34)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:39)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:23)
	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:129)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.sun.nio.zipfs.ZipPath.resolve0(ZipPath.java:497)
	at com.sun.nio.zipfs.ZipPath.getResolved(ZipPath.java:488)
	at com.sun.nio.zipfs.ZipPath.getResolvedPath(ZipPath.java:425)
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:664)
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.jetbrains.plugin.structure.classes.resolvers.JarFileResolver.readClassNamesAndServiceProviders(JarFileResolver.kt:61)
	at com.jetbrains.plugin.structure.classes.resolvers.JarFileResolver.<init>(JarFileResolver.kt:56)
	at com.jetbrains.plugin.structure.classes.resolvers.JarFileResolverKt.buildJarOrZipFileResolvers(JarFileResolver.kt:213)
	at com.jetbrains.plugin.structure.intellij.classes.locator.CompileServerExtensionLocator.findClasses(CompileServerExtensionLocator.kt:35)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder.findLocations(IdePluginClassesFinder.kt:64)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder.findPluginClasses(IdePluginClassesFinder.kt:42)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder.access$findPluginClasses(IdePluginClassesFinder.kt:22)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder$Companion.findPluginClasses(IdePluginClassesFinder.kt:105)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder$Companion.findPluginClasses(IdePluginClassesFinder.kt:92)
	at com.jetbrains.plugin.structure.intellij.classes.plugin.IdePluginClassesFinder$Companion.findPluginClasses(IdePluginClassesFinder.kt:84)
	at com.jetbrains.pluginverifier.plugin.PluginDetailsProviderImpl.readPluginClasses(PluginDetailsProviderImpl.kt:78)
	at com.jetbrains.pluginverifier.plugin.PluginDetailsProviderImpl.providePluginDetails(PluginDetailsProviderImpl.kt:43)
	at com.jetbrains.pluginverifier.plugin.PluginDetailsResourceProvider.provide(PluginDetailsCache.kt:135)

```

(We attempted to add `-Xmx4G` as a desperate move but it did not help)

**Comment by serejke** [comment] 2020-09-21 08:12
Hi, @yugecin. Thanks for filing this ticket!
Can you tell the plugin id you are developing?
I can't reproduce the problem with only `IU-162.1121.32` checked against another plugin.

I would appreciate if you ran the verification with `-XX:+HeapDumpOnOutOfMemoryError` enabled to collect the heap dump on `OutOfMemoryError` and published the dump to https://uploads.jetbrains.com/.

**Comment by yugecin** [comment] 2020-09-21 10:48
Hey @serejke thanks for responding,

Plugin id is `com.sensei.solutions`, available here: https://plugins.jetbrains.com/plugin/14015-sensei-by-secure-code-warrior-

Heap dump: Upload id: 2020_09_21_DVLpLZseSDF8vgQY (file: java_pid17908.zip)
(I've also added `-Xmx1G` or otherwise the dump file was 4GB, I've checked and using version 1.245 still completes successfully with this memory limitation.)

**Comment by serejke** [comment] 2020-09-21 18:57
Thank you, @yugecin! 
I have reproduced the problem! 

It is a bug in JDK 8 (https://bugs.openjdk.java.net/browse/JDK-8197398): `java.nio.Files.visit` infinitely walks some zip files that have zip entries like `someDir//` with the second `/` being the name of the directory. For some reason, the zip allows such entries :facepalm: While walking, the `FileVisitor` is recording files in an `ArrayList`, which at some point is overflowed.
When checking your plugin with IDE 2016.2 there is an invalid Kotlin's plugin zip archive that contains such a cyclic entry.

This bug is already fixed in JDK 11 (and maybe earlier).

Please confirm that you are running the Plugin Verifier with JDK 8 (by default, the Verifier uses the java from `JAVA_HOME`).

I will implement a workaround for JDK 8: while walking the file tree, we will check that we have not visited this directory yet.
Until the new version is available, please use JDK 11 for running the Verifier

**Closed** 2020-09-21 19:02 UTC

**Comment by serejke** [comment] 2020-09-21 19:17
Version 1.248 fix the workaround has been published! I would appreciate if you ran the Plugin Verifier 1.248 with JDK 8 to verify that the issue is gone. Thanks!

**Comment by yugecin** [comment] 2020-09-21 20:54
> Please confirm that you are running the Plugin Verifier with JDK 8

Correct.

The issue is gone with 1.248 on JDK 8.
Thank you for the update and the detailed information!
